### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [JamesPaynter/PyGRB#13]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?
The interface should be very similar to pymultinest.

UltraNest is a very reliable tuning-parameter-free algorithm. I have published some examples where the UltraNest algorithm is unbiased while multinest's algorithm (implemented in pymultinest,nestle,dynesty) gives a different answer. UltraNest is a pure-python package and very easy to install with pip or conda.

UltraNest also supports resuming from disk and MPI parallelisation, if that is useful to you.

Perhaps this is already possible for you through bilby.

**Comment by JamesPaynter** [comment]
Hi Johannes,

Sorry I only just saw this. I am not working on this project at the moment, but I am certainly not opposed to adding support for UltraNest. 

UltraNest is supported by Bilby, so it should only be a few lines of code, if that.

I will see what I can do,
James

**Comment by JamesPaynter** [comment]
Repo is no longer actively maintained
