### ISSUE TITLE
install warnings, "You will  not be able to use some of the prebuilt functions"

### ISSUE THREAD

**Issue by zingale** [JamesPaynter/PyGRB#6]
When doing:
```
from PyGRB.main.fitpulse import PulseFitter
```
I get the errors:
```
22:38 bilby WARNING : You do not have gwpy installed currently. You will  not be able to use some of the prebuilt functions.
22:38 bilby WARNING : You do not have lalsuite installed currently. You will not be able to use some of the prebuilt functions.
22:38 bilby WARNING : You do not have gwpy installed currently. You will  not be able to use some of the prebuilt functions.
22:38 bilby WARNING : You do not have lalsuite installed currently. You will not be able to use some of the prebuilt functions.
22:38 bilby WARNING : You do not have gwpy installed currently. You will  not be able to use some of the prebuilt functions.
22:38 bilby WARNING : You do not have lalsuite installed currently. You will not be able to use some of the prebuilt functions.
22:38 bilby WARNING : You do not have lalsuite installed currently. You will not be able to use some of the prebuilt functions.
```

These packages are not part of the `requirements.txt` and I don't see mention of them in the docs.  

Are these okay?  Perhaps the install docs should address this.

**Comment by zingale** [comment]
tagging: https://github.com/openjournals/joss-reviews/issues/2536

**Comment by JamesPaynter** [comment]
These packages are used in bilby.gw for gravitational wave inference.
PyGRB only uses bilby.core functionality for nested sampling and Bayesian inference, but these warnings appear anyway.
I am speaking with a member of the bilby team now to see if it is something to fix on their end.

I will make a note in the install section addressing this.

**Comment by JamesPaynter** [comment]
updated the documentation accordingly
https://pygrb.readthedocs.io/en/latest/user/readme.html
