### ISSUE TITLE
usage instructions don't result in all of the plots shown

### ISSUE THREAD

**Issue by zingale** [JamesPaynter/PyGRB#7]
Following the usage instructions here: https://pygrb.readthedocs.io/en/latest/user/usage.html

I get output in a `products` directory, which contains the first plot shown in the usage docs but not the others.

In particular, I don't get this plot: 
https://pygrb.readthedocs.io/en/latest/_images/trigger7475chan3.PNG

or the corner plot. 

The usage instructions should walk through how those plots are created.

**Comment by zingale** [comment]
tagging JOSS: https://github.com/openjournals/joss-reviews/issues/2536

**Comment by JamesPaynter** [comment]
The corner plot should have been there? It may have been saved as a pdf. 
I updated the corner plot to save as png, I also fixed a bug that was stopping the correlogram and residual probability plot from displaying properly. 
I pushed an edit with the changes (to GitHub but not to PyPI)
Let me know if they are still not displaying properly

James

**Comment by zingale** [comment]
indeed, the corner plot is there as PNG now. And I now see the one above -- I must have missed it somehow previously.

I think it might be helpful to explain what a user should expect to see in the products/ directory.

**Comment by JamesPaynter** [comment]
Awesome :) 
There was a bug in that the marker size for the lower plots was too small, I guess it must have been smaller than one pixel for the given plot dimensions. So thank you for bringing that to my attention.
And they were not plotting by default, which I have fixed now.

I updated the docs to more clearly reflect the product files
https://pygrb.readthedocs.io/en/latest/user/usage.html
