### ISSUE TITLE
JOSS review: contributor guidelines

### ISSUE THREAD

**Issue by zingale** [JamesPaynter/PyGRB#8]
JOSS requires:

> ￼ Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

The only contribution information I see is at the bottom of the README.md, which looks more like a TODO list.  

Can you expand this section, perhaps explaining that contributions are welcomed in the form of PRs against this repo, support is via issues, etc.

**Comment by zingale** [comment]
tagging JOSS: https://github.com/openjournals/joss-reviews/issues/2536

**Comment by JamesPaynter** [comment]
I updated the contribute section of the readme to reflect JOSS's community guidelines.
Cheers,
James

**Comment by zingale** [comment]
awesome.  Thanks.
